import os

Import('env')

penv = env.Clone()

src = [
    "ddh_test.cpp",
    "params_test.cpp",
    "vrf_test.cpp",
]

penv.Append(LIBS = ["gtest", "gtest_main", "pthread"], 
  CPPFLAGS = ["-I/usr/local/include", "-I."],
  LIBPATH = ["/usr/local/lib"])

penv.Program("dettest", src)

